-- ============================================================================
-- 000-setup-tests-hooks.sql
--
-- pgTAP + supabase-test-helpers の共通セットアップ。
-- `supabase test db` はアルファベット順でファイルを評価するため、
-- このファイル名（000- プレフィックス）で必ず最初に実行される。
--
-- 詳細は .claude/skills/pgtap/SKILL.md を参照。
-- ============================================================================

-- pgTAP 拡張を有効化（extensions スキーマに配置して public を汚さない）
create extension if not exists pgtap with schema extensions;

-- ----------------------------------------------------------------------------
-- supabase-test-helpers を tests スキーマにロード
--
-- 提供される関数:
--   tests.create_supabase_user(identifier, email?, phone?, metadata?)
--   tests.authenticate_as(identifier)
--   tests.authenticate_as_service_role()
--   tests.clear_authentication()
--   tests.get_supabase_uid(identifier)
--
-- インストール方法は helpers のバージョンにより異なる:
--   - https://github.com/usebasejump/supabase-test-helpers の最新 SQL を
--     このファイルに取り込む、あるいは別ファイル（例: 000-helpers.sql）に分離する
--   - 初回セットアップ時に database.dev / dbdev 経由でインストールする場合もある
--
-- このファイルは helpers がまだ手元にない状態で残しているため、
-- 実テストを書き始める前に helpers のロード手順を追加すること。
-- ----------------------------------------------------------------------------
