/**
 * OpenAPI TypeScript 型生成スクリプト
 *
 * バックエンドの OpenAPI スキーマから TypeScript 型定義を生成する
 *
 * 使用方法:
 *   bun run scripts/generate.ts
 *
 * 環境変数:
 *   BACKEND_URL - バックエンド API の URL (デフォルト: http://127.0.0.1:4040)
 */

import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { $ } from 'bun'

const __dirname = dirname(fileURLToPath(import.meta.url))
const packageDir = join(__dirname, '..')
const outputPath = join(packageDir, 'src', 'schema.d.ts')

// バックエンド URL を環境変数から取得（デフォルト: ローカル開発環境）
const backendUrl =
  process.env.BACKEND_URL ?? process.env.NEXT_PUBLIC_BACKEND_PY_URL ?? 'http://127.0.0.1:4040'
const openapiUrl = `${backendUrl}/openapi.json`

async function checkBackendAvailable(): Promise<boolean> {
  try {
    const response = await fetch(`${backendUrl}/healthcheck`, {
      method: 'GET',
      signal: AbortSignal.timeout(5000),
    })
    return response.ok
  } catch {
    return false
  }
}

async function generate() {
  console.log('🔍 Checking backend availability...')
  console.log(`   Backend URL: ${backendUrl}`)

  const isAvailable = await checkBackendAvailable()

  if (!isAvailable) {
    console.warn('⚠️  Backend is not available. Skipping type generation.')
    console.warn('   Make sure the backend is running: make run')

    // 既存のスキーマファイルがあればそれを使用
    if (existsSync(outputPath)) {
      console.log('ℹ️  Using existing schema.d.ts')
      return
    }

    // スキーマファイルがない場合は空のファイルを作成
    console.log('📝 Creating placeholder schema.d.ts')
    await Bun.write(
      outputPath,
      `// Auto-generated by openapi-typescript
// This is a placeholder file. Run 'bun run generate' with backend running to generate actual types.

export interface paths {}
export interface components {}
export interface operations {}
export type external = Record<string, never>
`
    )
    return
  }

  console.log('✅ Backend is available')
  console.log(`🚀 Generating types from ${openapiUrl}...`)

  try {
    // openapi-typescript CLI を使用して型を生成
    await $`bunx openapi-typescript ${openapiUrl} -o ${outputPath}`
    console.log(`✨ Generated: ${outputPath}`)
  } catch (error) {
    console.error('❌ Failed to generate types:', error)
    process.exit(1)
  }
}

generate()
