import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { colors, radius, toKebabCase } from '../src'

const __dirname = dirname(fileURLToPath(import.meta.url))
const packageRoot = resolve(__dirname, '..')

function generateWebCSS(): string {
  const lightVars = Object.entries(colors.light)
    .map(([key, value]) => `  --${toKebabCase(key)}: ${value};`)
    .join('\n')

  const darkVars = Object.entries(colors.dark)
    .map(([key, value]) => `  --${toKebabCase(key)}: ${value};`)
    .join('\n')

  return `/* Auto-generated by @workspace/tokens - DO NOT EDIT */

:root {
  --radius: ${radius.base};
${lightVars}
}

.dark {
${darkVars}
}
`
}

function generateNativeCSS(): string {
  const lightVars = Object.entries(colors.light)
    .map(([key, value]) => `  --${toKebabCase(key)}: ${value};`)
    .join('\n')

  const darkVars = Object.entries(colors.dark)
    .map(([key, value]) => `  --${toKebabCase(key)}: ${value};`)
    .join('\n')

  return `/* Auto-generated by @workspace/tokens - DO NOT EDIT */
@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css";
@import "nativewind/theme";

:root {
  --radius: ${radius.base};
${lightVars}
}

.dark {
${darkVars}
}
`
}

// Generate files
writeFileSync(resolve(packageRoot, 'web.css'), generateWebCSS())
writeFileSync(resolve(packageRoot, 'native.css'), generateNativeCSS())

console.log('CSS files generated successfully!')
console.log(`  - ${resolve(packageRoot, 'web.css')}`)
console.log(`  - ${resolve(packageRoot, 'native.css')}`)
