import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { colors, radius, toKebabCase } from '../src'

const __dirname = dirname(fileURLToPath(import.meta.url))
const packageRoot = resolve(__dirname, '..')

const BANNER = '/* Auto-generated by @workspace/tokens - DO NOT EDIT (run `tokens:build`) */'

function toCssVars(mode: 'light' | 'dark', indent = '  '): string {
  return Object.entries(colors[mode])
    .map(([key, value]) => `${indent}--${toKebabCase(key)}: ${value};`)
    .join('\n')
}

/**
 * Tailwind v4 の `@theme inline` マッピング。
 * `--color-*` / `--radius-*` を宣言することで `bg-primary` `rounded-lg` などの
 * ユーティリティが生成される。Web / Native で同じユーティリティ名を使えるようにする。
 */
function themeMapping(): string {
  const colorMapping = Object.keys(colors.light)
    .map((key) => {
      const name = toKebabCase(key)
      return `  --color-${name}: var(--${name});`
    })
    .join('\n')

  const radiusMapping = Object.entries(radius)
    .filter(([key]) => key !== 'base')
    .map(([key, value]) => `  --radius-${key}: ${value};`)
    .join('\n')

  return `${colorMapping}\n${radiusMapping}`
}

/**
 * Web / Desktop 向け。
 *
 * ダークモードは `.dark` クラス（shadcn/ui・next-themes 準拠）で切り替える。
 * Electron / Tauri など Web 技術ベースのデスクトップアプリもこのファイルをそのまま利用できる。
 */
function generateWebCSS(): string {
  return `${BANNER}

@theme inline {
${themeMapping()}
}

:root {
  --radius: ${radius.base};
${toCssVars('light')}
}

.dark {
${toCssVars('dark')}
}
`
}

/**
 * React Native (Expo + NativeWind v5 / react-native-css) 向け。
 *
 * ネイティブには `.dark` クラスを付与する DOM が無いため、ダークモードは
 * `@media (prefers-color-scheme: dark)`（= 端末のカラースキーム）で切り替える。
 * Web 版と同じ `--color-*` マッピングを持つので、ユーティリティ名は完全に共通。
 */
function generateNativeCSS(): string {
  return `${BANNER}
@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css";
@import "nativewind/theme";

@theme inline {
${themeMapping()}
}

:root {
  --radius: ${radius.base};
${toCssVars('light')}
}

@media (prefers-color-scheme: dark) {
  :root {
${toCssVars('dark', '    ')}
  }
}
`
}

writeFileSync(resolve(packageRoot, 'web.css'), generateWebCSS())
writeFileSync(resolve(packageRoot, 'native.css'), generateNativeCSS())

console.log('CSS files generated successfully!')
console.log(`  - ${resolve(packageRoot, 'web.css')}`)
console.log(`  - ${resolve(packageRoot, 'native.css')}`)
